from __future__ import annotations

import csv
import io
import os
import secrets
import threading
import time
import webbrowser
from datetime import datetime, timedelta, timezone
from functools import wraps

from flask import Flask, Response, flash, jsonify, redirect, render_template, request, session, url_for

from firebase_cloud import FirebaseCloudStore
from face_engine import (
    build_or_get_model, crop_to_jpeg, decode_data_url, get_cached_model, identify_frames,
    invalidate_class_model, liveness_baseline, verify_liveness_action,
)

app = Flask(__name__)
app.secret_key = os.environ.get("FLASK_SECRET_KEY") or secrets.token_hex(32)
app.config.update(
    SESSION_COOKIE_HTTPONLY=True,
    SESSION_COOKIE_SAMESITE="Lax",
    MAX_CONTENT_LENGTH=16 * 1024 * 1024,
    SEND_FILE_MAX_AGE_DEFAULT=0,
)
cloud = FirebaseCloudStore()

# In-memory, short-lived challenge state. Challenges are generated by the server,
# expire quickly, are tied to one teacher/session, and are single-use.
_LIVENESS_CHALLENGES = {}
_LIVENESS_LOCK = threading.RLock()
_LIVENESS_TTL = 150.0


def _cleanup_liveness():
    now = time.monotonic()
    with _LIVENESS_LOCK:
        stale = [key for key, value in _LIVENESS_CHALLENGES.items() if now - value.get("created_mono", now) > 120.0]
        for key in stale:
            _LIVENESS_CHALLENGES.pop(key, None)


def _liveness_record(challenge_id: str, teacher_id: str, session_id: str):
    _cleanup_liveness()
    with _LIVENESS_LOCK:
        item = _LIVENESS_CHALLENGES.get(challenge_id)
        if not item:
            return None
        if item.get("teacher_id") != teacher_id or item.get("session_id") != session_id:
            return None
        if time.monotonic() - item.get("created_mono", 0.0) > _LIVENESS_TTL:
            _LIVENESS_CHALLENGES.pop(challenge_id, None)
            return None
        return item


IST = timezone(timedelta(hours=5, minutes=30))


def format_ist(value):
    """Convert an ISO timestamp stored in UTC to Indian Standard Time for display."""
    if not value:
        return "-"
    try:
        dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(IST).strftime("%d-%m-%Y %I:%M:%S %p")
    except (ValueError, TypeError):
        return str(value)


app.jinja_env.filters["ist_time"] = format_ist


@app.after_request
def disable_local_cache(response):
    # This is a local classroom app. Disable browser caching so language/theme
    # JavaScript updates are visible immediately after a project update.
    response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "0"
    return response


def firebase_ready() -> bool:
    return cloud.app is not None


def current_teacher():
    tid = session.get("teacher_id")
    if not tid or not firebase_ready():
        return None
    try:
        return cloud.get_teacher(tid)
    except Exception:
        return None


def firebase_required(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if not firebase_ready():
            return redirect(url_for("firebase_setup"))
        return fn(*args, **kwargs)
    return wrapper


def teacher_required(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if not current_teacher():
            return redirect(url_for("login"))
        return fn(*args, **kwargs)
    return wrapper


@app.context_processor
def inject_globals():
    ok, text = cloud.status()
    return {"me": current_teacher(), "firebase_connected": ok, "firebase_text": text}


@app.route("/")
def home():
    if not firebase_ready():
        return redirect(url_for("firebase_setup"))
    return redirect(url_for("teacher_dashboard") if current_teacher() else url_for("login"))


@app.route("/setup/firebase", methods=["GET", "POST"])
def firebase_setup():
    if request.method == "POST":
        file = request.files.get("service_account")
        database_url = request.form.get("database_url", "")
        if not file or not file.filename:
            flash("Select the Firebase service-account JSON file.", "error")
        else:
            try:
                cloud.save_configuration(database_url, file.read())
                flash("Firebase Realtime Database connected successfully.", "success")
                return redirect(url_for("login"))
            except Exception as exc:
                flash(f"Firebase setup failed: {exc}", "error")
    return render_template("firebase_setup.html")


@app.route("/login", methods=["GET", "POST"])
@firebase_required
def login():
    if current_teacher():
        return redirect(url_for("teacher_dashboard"))
    if request.method == "POST":
        try:
            teacher = cloud.authenticate_teacher(request.form.get("email", ""), request.form.get("password", ""))
        except Exception as exc:
            flash(f"Firebase error: {exc}", "error")
            teacher = None
        if teacher:
            session.clear()
            session["teacher_id"] = teacher["teacher_id"]
            return redirect(url_for("teacher_dashboard"))
        flash("Invalid teacher email or password.", "error")
    return render_template("login.html")


@app.route("/teacher/register", methods=["GET", "POST"])
@firebase_required
def teacher_register():
    if request.method == "POST":
        try:
            teacher = cloud.create_teacher(
                request.form.get("name", ""),
                request.form.get("email", ""),
                request.form.get("password", ""),
            )
            session.clear()
            session["teacher_id"] = teacher["teacher_id"]
            flash("Teacher account created. Your classes will be stored under your own Firebase namespace.", "success")
            return redirect(url_for("teacher_dashboard"))
        except ValueError as exc:
            flash(str(exc), "error")
    return render_template("teacher_register.html")


@app.get("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))


@app.get("/teacher")
@firebase_required
@teacher_required
def teacher_dashboard():
    teacher = current_teacher()
    classes = cloud.list_classes(teacher["teacher_id"])
    sessions = cloud.list_sessions(teacher["teacher_id"])
    students_count = sum(len(cloud.list_students(teacher["teacher_id"], c["class_id"])) for c in classes)
    attendance_count = cloud.attendance_count_for_teacher(teacher["teacher_id"])
    return render_template(
        "teacher_dashboard.html",
        classes=classes,
        classes_map={c["class_id"]: c for c in classes},
        sessions=sessions[:20],
        students_count=students_count,
        attendance_count=attendance_count,
    )


@app.post("/teacher/classes/create")
@firebase_required
@teacher_required
def create_class_route():
    try:
        cloud.create_class(current_teacher()["teacher_id"], request.form.get("name", ""), request.form.get("section", ""))
        flash("Class bucket created in Firebase.", "success")
    except ValueError as exc:
        flash(str(exc), "error")
    return redirect(url_for("teacher_dashboard"))


@app.get("/teacher/class/<class_id>")
@firebase_required
@teacher_required
def teacher_class(class_id: str):
    tid = current_teacher()["teacher_id"]
    clazz = cloud.get_class(tid, class_id)
    if not clazz:
        flash("Class not found.", "error")
        return redirect(url_for("teacher_dashboard"))
    students = cloud.list_students(tid, class_id)
    return render_template("teacher_class.html", clazz=clazz, students=students)


@app.post("/teacher/class/<class_id>/students/add")
@firebase_required
@teacher_required
def add_student_route(class_id: str):
    try:
        cloud.add_student(current_teacher()["teacher_id"], class_id, request.form.get("name", ""), request.form.get("student_id", ""))
        flash("Student added to this class in Firebase.", "success")
    except ValueError as exc:
        flash(str(exc), "error")
    return redirect(url_for("teacher_class", class_id=class_id))


@app.get("/teacher/class/<class_id>/student/<student_id>/face-enroll")
@firebase_required
@teacher_required
def teacher_face_enroll(class_id: str, student_id: str):
    tid = current_teacher()["teacher_id"]
    clazz = cloud.get_class(tid, class_id)
    student = cloud.get_student(tid, class_id, student_id)
    if not clazz or not student:
        flash("Student not found in this class.", "error")
        return redirect(url_for("teacher_dashboard"))
    return render_template("face_enroll.html", clazz=clazz, student=student)


@app.post("/api/teacher/class/<class_id>/student/<student_id>/face/reset")
@firebase_required
@teacher_required
def face_reset_api(class_id: str, student_id: str):
    tid = current_teacher()["teacher_id"]
    try:
        cloud.reset_face_samples(tid, class_id, student_id)
        invalidate_class_model(f"{tid}:{class_id}")
        return jsonify({"ok": True})
    except Exception as exc:
        return jsonify({"ok": False, "message": str(exc)}), 400


@app.post("/api/teacher/class/<class_id>/student/<student_id>/face/sample")
@firebase_required
@teacher_required
def face_sample_api(class_id: str, student_id: str):
    tid = current_teacher()["teacher_id"]
    student = cloud.get_student(tid, class_id, student_id)
    if not student:
        return jsonify({"ok": False, "message": "Student not found in this class."}), 404
    data = request.get_json(silent=True) or {}
    frame = data.get("frame", "")
    if not frame:
        return jsonify({"ok": False, "message": "No camera frame received."}), 400
    try:
        jpeg = crop_to_jpeg(decode_data_url(frame))
        count = int(student.get("sample_count", 0))
        if jpeg is None:
            return jsonify({"ok": True, "accepted": False, "count": count})
        next_count = min(count + 1, 20)
        cloud.save_face_sample(tid, class_id, student_id, next_count, jpeg)
        enrolled = next_count >= 20
        cloud.update_student_face_state(tid, class_id, student_id, next_count, enrolled)
        invalidate_class_model(f"{tid}:{class_id}")
        return jsonify({"ok": True, "accepted": True, "count": next_count, "enrolled": enrolled})
    except Exception as exc:
        return jsonify({"ok": False, "message": str(exc)}), 400


@app.post("/teacher/session/start")
@firebase_required
@teacher_required
def start_session_route():
    tid = current_teacher()["teacher_id"]
    try:
        item = cloud.start_session(tid, request.form.get("class_id", ""), int(request.form.get("duration", "20")))
        # Warm the in-memory class recognizer from Firebase face samples before the first student arrives.
        samples = cloud.download_class_faces(tid, item["class_id"])
        build_or_get_model(f"{tid}:{item['class_id']}", cloud.class_model_version(tid, item["class_id"]), samples)
        return redirect(url_for("classroom_kiosk", session_id=item["session_id"]))
    except Exception as exc:
        flash(str(exc), "error")
        return redirect(url_for("teacher_dashboard"))


def _teacher_session(session_id: str):
    teacher = current_teacher()
    if not teacher:
        return None
    return cloud.find_session(teacher["teacher_id"], session_id)


@app.post("/teacher/session/<session_id>/stop")
@firebase_required
@teacher_required
def stop_session_route(session_id: str):
    item = _teacher_session(session_id)
    if not item:
        flash("Session not found.", "error")
        return redirect(url_for("teacher_dashboard"))
    try:
        cloud.stop_session(current_teacher()["teacher_id"], item["class_id"], session_id)
        flash("Attendance ended. The classroom kiosk is now closed.", "success")
    except ValueError as exc:
        flash(str(exc), "error")
    return redirect(url_for("teacher_session", session_id=session_id))


@app.get("/teacher/session/<session_id>")
@firebase_required
@teacher_required
def teacher_session(session_id: str):
    tid = current_teacher()["teacher_id"]
    item = _teacher_session(session_id)
    if not item:
        flash("Session not found.", "error")
        return redirect(url_for("teacher_dashboard"))
    clazz = cloud.get_class(tid, item["class_id"]) or {}
    records = cloud.attendance_for_session(tid, item["class_id"], session_id)
    students = cloud.list_students(tid, item["class_id"])
    return render_template("teacher_session.html", attendance_session=item, clazz=clazz, records=records, active=cloud.session_active(item), students=students)


@app.get("/teacher/session/<session_id>/export")
@firebase_required
@teacher_required
def export_session(session_id: str):
    tid = current_teacher()["teacher_id"]
    item = _teacher_session(session_id)
    if not item:
        return redirect(url_for("teacher_dashboard"))
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["Student ID", "Name", "Marked At IST", "Face Score", "Liveness", "Status"])
    for row in cloud.attendance_for_session(tid, item["class_id"], session_id):
        writer.writerow([row.get("student_id"), row.get("student_name"), format_ist(row.get("marked_at")), row.get("face_distance"), "Verified" if row.get("liveness_verified") else "-", row.get("status")])
    return Response(output.getvalue(), mimetype="text/csv", headers={"Content-Disposition": f"attachment; filename=attendance_{session_id}.csv"})


@app.get("/kiosk/<session_id>")
@firebase_required
@teacher_required
def classroom_kiosk(session_id: str):
    tid = current_teacher()["teacher_id"]
    item = _teacher_session(session_id)
    if not item:
        flash("Attendance session not found.", "error")
        return redirect(url_for("teacher_dashboard"))
    if not cloud.session_active(item):
        flash("The kiosk is available only while attendance is active.", "error")
        return redirect(url_for("teacher_session", session_id=session_id))
    clazz = cloud.get_class(tid, item["class_id"]) or {}
    records = cloud.attendance_for_session(tid, item["class_id"], session_id)
    enrolled = [s for s in cloud.list_students(tid, item["class_id"]) if s.get("face_enrolled")]
    return render_template("classroom_kiosk.html", attendance_session=item, clazz=clazz, records=records, enrolled=enrolled)


@app.post("/api/kiosk/<session_id>/liveness/challenge")
@firebase_required
@teacher_required
def kiosk_liveness_challenge_api(session_id: str):
    tid = current_teacher()["teacher_id"]
    item = _teacher_session(session_id)
    if not item or not cloud.session_active(item):
        return jsonify({"ok": False, "session_closed": True, "message": "Attendance is closed."}), 400
    challenge_id = secrets.token_urlsafe(18)
    rng = secrets.SystemRandom()
    # Two-step challenge using only blink and smile. Each attempt contains
    # exactly one blink step and one smile step in a fresh cryptographically
    # randomized order. The server keeps the full sequence private and reveals
    # only the current action after the previous one passes.
    actions = ["blink", "smile"]
    rng.shuffle(actions)
    with _LIVENESS_LOCK:
        _LIVENESS_CHALLENGES[challenge_id] = {
            "teacher_id": tid,
            "session_id": session_id,
            "class_id": item["class_id"],
            "created_mono": time.monotonic(),
            "actions": actions,
            "index": 0,
            "baseline": None,
            "passed": False,
            "used": False,
            "verify_attempts": 0,
        }
    return jsonify({
        "ok": True,
        "challenge_id": challenge_id,
        "first_action": actions[0],
        "total_steps": len(actions),
        "expires_in": int(_LIVENESS_TTL),
    })


@app.post("/api/kiosk/<session_id>/liveness/baseline")
@firebase_required
@teacher_required
def kiosk_liveness_baseline_api(session_id: str):
    tid = current_teacher()["teacher_id"]
    data = request.get_json(silent=True) or {}
    challenge_id = str(data.get("challenge_id", ""))
    frames = data.get("frames") or []
    item = _liveness_record(challenge_id, tid, session_id)
    if not item:
        return jsonify({"ok": False, "message": "Liveness challenge expired. Start again."}), 400
    if len(frames) < 4:
        return jsonify({"ok": False, "message": "Keep your face centered for calibration."}), 400
    try:
        baseline = liveness_baseline([decode_data_url(x) for x in frames[:8]])
        with _LIVENESS_LOCK:
            item["baseline"] = baseline
        return jsonify({"ok": True, "usable": int(baseline.get("usable", 0))})
    except Exception as exc:
        return jsonify({"ok": False, "message": str(exc)}), 400


@app.post("/api/kiosk/<session_id>/liveness/step")
@firebase_required
@teacher_required
def kiosk_liveness_step_api(session_id: str):
    tid = current_teacher()["teacher_id"]
    data = request.get_json(silent=True) or {}
    challenge_id = str(data.get("challenge_id", ""))
    action = str(data.get("action", ""))
    frames = data.get("frames") or []
    item = _liveness_record(challenge_id, tid, session_id)
    if not item:
        return jsonify({"ok": False, "message": "Liveness challenge expired. Start again."}), 400
    if item.get("used"):
        return jsonify({"ok": False, "message": "This liveness challenge was already used."}), 400
    if item.get("passed"):
        return jsonify({"ok": True, "passed": True, "complete": True, "next_index": len(item.get("actions", []))})
    if not item.get("baseline"):
        return jsonify({"ok": False, "message": "Neutral face calibration is required first."}), 400
    index = int(item.get("index", 0))
    actions = item.get("actions") or []
    if index >= len(actions):
        return jsonify({"ok": False, "message": "Invalid liveness state."}), 400
    expected = actions[index]
    if action != expected:
        return jsonify({"ok": False, "message": "Liveness action is out of sequence."}), 400
    if len(frames) < 5:
        return jsonify({"ok": False, "message": "Not enough camera frames for this action."}), 400
    try:
        passed, message, diagnostics = verify_liveness_action(
            action, [decode_data_url(x) for x in frames[:18]], item["baseline"]
        )
        if passed:
            with _LIVENESS_LOCK:
                item["index"] = index + 1
                complete = item["index"] >= len(actions)
                if complete:
                    item["passed"] = True
                    item["passed_mono"] = time.monotonic()
            next_action = None if complete else actions[index + 1]
            return jsonify({
                "ok": True, "passed": True, "complete": complete,
                "next_index": index + 1, "next_action": next_action,
                "message": message, "diagnostics": diagnostics,
            })
        return jsonify({"ok": True, "passed": False, "complete": False, "message": message, "diagnostics": diagnostics})
    except Exception as exc:
        return jsonify({"ok": False, "message": str(exc)}), 400


@app.post("/api/kiosk/<session_id>/verify")
@firebase_required
@teacher_required
def kiosk_verify_api(session_id: str):
    tid = current_teacher()["teacher_id"]
    item = _teacher_session(session_id)
    if not item or not cloud.session_active(item):
        return jsonify({"ok": False, "session_closed": True, "message": "Attendance is closed."}), 400
    class_id = item["class_id"]
    students = cloud.list_students(tid, class_id)
    allowed = {s["student_id"].upper() for s in students if s.get("face_enrolled")}
    if not allowed:
        return jsonify({"ok": False, "message": "No enrolled face profiles are available for this class."}), 400

    data = request.get_json(silent=True) or {}
    liveness_token = str(data.get("liveness_token", ""))
    live = _liveness_record(liveness_token, tid, session_id)
    if not live or not live.get("passed") or live.get("used"):
        return jsonify({"ok": False, "liveness_required": True, "message": "Complete the random liveness challenge before face recognition."}), 403
    # Keep the passed liveness token alive for at most two immediate identity
    # captures. This avoids forcing the student through the full liveness
    # sequence again just because one final frame burst was blurred/off-center.
    # The token is still short-lived and is consumed on success or after two
    # identity attempts.
    with _LIVENESS_LOCK:
        attempts = int(live.get("verify_attempts", 0)) + 1
        live["verify_attempts"] = attempts
        if attempts > 2:
            live["used"] = True
            return jsonify({"ok": False, "liveness_required": True, "message": "Identity retry limit reached. Start a new liveness challenge."}), 403
    frames = data.get("frames") or []
    if len(frames) < 4:
        return jsonify({"ok": False, "message": "Face verification needs several camera frames."}), 400
    try:
        cache_key = f"{tid}:{class_id}"
        version = cloud.class_model_version(tid, class_id)
        cached = get_cached_model(cache_key, version)
        if cached:
            recognizer, label_map = cached
        else:
            samples = cloud.download_class_faces(tid, class_id)
            recognizer, label_map = build_or_get_model(cache_key, version, samples)
        raw_frames = [decode_data_url(frame) for frame in frames[:10]]
        student_id, face_distance, usable, matching = identify_frames(
            raw_frames, recognizer, label_map, allowed_student_ids=allowed, threshold=75.0
        )
        if not student_id:
            with _LIVENESS_LOCK:
                retry_allowed = int(live.get("verify_attempts", 0)) < 2
                if not retry_allowed:
                    live["used"] = True
            message = "Face match was unclear. Return to the center, look straight at the camera, and keep still."
            if not retry_allowed:
                message += " Start secure verification again."
            return jsonify({
                "ok": False, "retry_identity": retry_allowed, "message": message,
                "usable_frames": usable, "matching_frames": matching,
                "best_distance": None if face_distance >= 998 else round(float(face_distance), 2),
            }), 403
        try:
            record = cloud.mark_attendance(tid, class_id, session_id, student_id, face_distance, liveness_actions=live.get("actions", []))
        except ValueError as exc:
            if "already marked" in str(exc).lower():
                student = cloud.get_student(tid, class_id, student_id) or {"name": student_id}
                with _LIVENESS_LOCK:
                    live["used"] = True
                return jsonify({"ok": False, "already": True, "message": f"{student.get('name')} ({student_id}) is already marked present.", "student": student}), 409
            raise
        with _LIVENESS_LOCK:
            live["used"] = True
        return jsonify({"ok": True, "message": "Identity verified. Attendance marked in Firebase.", "student": {"name": record["student_name"], "student_id": student_id}, "record": record, "matching_frames": matching})
    except Exception as exc:
        return jsonify({"ok": False, "message": str(exc)}), 400


@app.get("/api/kiosk/<session_id>/status")
@firebase_required
@teacher_required
def kiosk_status_api(session_id: str):
    tid = current_teacher()["teacher_id"]
    item = _teacher_session(session_id)
    if not item:
        return jsonify({"active": False, "present": 0, "records": []}), 404
    records = cloud.attendance_for_session(tid, item["class_id"], session_id)
    return jsonify({
        "active": cloud.session_active(item),
        "present": len(records),
        "records": [{"student_id": r.get("student_id"), "name": r.get("student_name"), "marked_at": format_ist(r.get("marked_at"))} for r in records[:8]],
    })


if __name__ == "__main__":
    print("\nAttendEase Secure v8 Blink + Smile 2x Random Liveness")
    print("Open: http://127.0.0.1:5055")
    if not firebase_ready():
        print("First run: connect Firebase Realtime Database in the setup page.")
    threading.Timer(1.0, lambda: webbrowser.open("http://127.0.0.1:5055")).start()
    app.run(host="0.0.0.0", port=5055, debug=False, threaded=True)
